'use client';

import { useChainId, useReadContract } from 'wagmi';
import { BadgeCheck, CreditCard, KeyRound, Users } from 'lucide-react';
import { use7702 } from '@/hooks/use7702';
import { useX402 } from '@/hooks/useX402';
import { useOnchainProof } from '@/hooks/useOnchainProof';
import { Badge } from '@/components/ui/Badge';
import { explorerTxUrl } from '@/lib/explorer';
import { getChainById } from '@/lib/superchain';
import { TrendingUp, DollarSign } from 'lucide-react';
import { formatUnits } from 'viem';

function shortHash(value: string, head = 10, tail = 6) {
  if (!value) return '';
  if (value.length <= head + tail + 3) return value;
  return `${value.slice(0, head)}…${value.slice(-tail)}`;
}

function KPIItem({
  label,
  value,
  sub,
  icon,
}: {
  label: string;
  value: React.ReactNode;
  sub?: React.ReactNode;
  icon: React.ReactNode;
}) {
  return (
    <div className="rounded-2xl border border-white/10 bg-black/30 px-4 py-3">
      <div className="flex items-center justify-between">
        <div className="text-[10px] uppercase tracking-[0.24em] text-zinc-500">{label}</div>
        <div className="text-zinc-400">{icon}</div>
      </div>
      <div className="mt-2 text-2xl font-semibold text-white">{value}</div>
      {sub ? <div className="mt-1 text-xs text-zinc-400">{sub}</div> : null}
    </div>
  );
}

const ERC20_ABI = [
  {
    name: 'totalSupply',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
] as const;

export function KPIBar() {
  const chainId = useChainId();
  const chain = getChainById(chainId);
  const { hasDelegated } = use7702();
  const { lastPayment, serviceInfo } = useX402();
  const { agentCount, agentId, registryHasCode } = useOnchainProof();

  const paymentLink = lastPayment ? explorerTxUrl(chainId, lastPayment.txHash) : null;
  const deployTone = registryHasCode === null ? 'neutral' : registryHasCode ? 'ok' : 'warn';
  const deployLabel = registryHasCode === null ? 'Unknown' : registryHasCode ? 'Deployed' : 'No bytecode';

  // Read real TVL from NexusUSD on both chains
  const baseNexusUSD = process.env.NEXT_PUBLIC_SUPERCHAIN_ERC20_BASE_SEPOLIA as `0x${string}` | undefined;
  const opNexusUSD = process.env.NEXT_PUBLIC_SUPERCHAIN_ERC20_OP_SEPOLIA as `0x${string}` | undefined;

  const { data: baseTVL } = useReadContract({
    address: baseNexusUSD,
    abi: ERC20_ABI,
    functionName: 'totalSupply',
    chainId: 84532, // Base Sepolia
  });

  const { data: opTVL } = useReadContract({
    address: opNexusUSD,
    abi: ERC20_ABI,
    functionName: 'totalSupply',
    chainId: 11155420, // OP Sepolia
  });

  // Calculate total TVL across both chains
  const totalTVL = 
    baseTVL && opTVL 
      ? Number(formatUnits(baseTVL, 18)) + Number(formatUnits(opTVL, 18))
      : baseTVL 
        ? Number(formatUnits(baseTVL, 18))
        : opTVL
          ? Number(formatUnits(opTVL, 18))
          : null;

  const totalValueSecured = totalTVL !== null 
    ? `$${totalTVL.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
    : '—';

  // TODO: Replace with real profit calculation from agent execution history
  const totalProfitGenerated = "+$12.5k";

  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 shadow-[0_1px_0_rgba(255,255,255,0.06)] backdrop-blur-xl">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="text-[10px] uppercase tracking-[0.28em] text-zinc-500">Proof snapshot</div>
          <div className="mt-1 text-sm text-zinc-300">Live chain state + wallet signals.</div>
        </div>
        <div className="flex items-center gap-2">
          <Badge tone={chain ? 'ok' : 'warn'}>
            {chain ? chain.label : `Chain ${chainId}`}
          </Badge>
          <Badge tone={deployTone}>{deployLabel}</Badge>
        </div>
      </div>

      <div className="mt-4 grid gap-3 md:grid-cols-4">
        <KPIItem label="Your agentId" value={agentId ? `#${agentId.toString()}` : '—'} icon={<BadgeCheck className="h-4 w-4" />} />
        <KPIItem label="Total agents" value={agentCount !== null ? agentCount.toString() : '—'} icon={<Users className="h-4 w-4" />} />
        <KPIItem label="Permissions" value={hasDelegated ? 'Active' : 'Inactive'} sub={hasDelegated ? 'EIP-7702 signed' : 'Sign delegation'} icon={<KeyRound className="h-4 w-4" />} />
        <KPIItem label="TVL Secured" value={totalValueSecured} sub="Aggregated across Superchain" icon={<DollarSign className="h-4 w-4" />} />
        <KPIItem label="Total Profit" value={<span className="text-emerald-400">{totalProfitGenerated}</span>} sub="Generated by Agents" icon={<TrendingUp className="h-4 w-4" />} />
        <KPIItem
          label="Last payment"
          value={lastPayment ? `${lastPayment.amount} ${serviceInfo?.asset || 'USDC'}` : '—'}
          icon={<CreditCard className="h-4 w-4" />}
          sub={
            lastPayment ? (
              paymentLink ? (
                <a href={paymentLink} target="_blank" rel="noreferrer" className="font-mono text-zinc-100 hover:underline">
                  {shortHash(lastPayment.txHash)}
                </a>
              ) : (
                <span className="font-mono">{shortHash(lastPayment.txHash)}</span>
              )
            ) : (
              'No payment yet'
            )
          }
        />
      </div>
    </div>
  );
}
